### ISSUE TITLE
Internet Connection

### ISSUE THREAD

**Issue by Georgerivi** [dps910/Dell-Optiplex-7010-Hackintosh-OpenCore#12]
Do i need internet connection to run the installation?
Because, I've been getting an error "installation requires downloading important content".

**Comment by dps-910** [comment]
You don't need an internet connection for installation if you download the full installer of Monterey using a macOS VM, and the createinstallmedia command to your USB https://support.apple.com/en-gb/101578

I'd recommend Monterey on this PC because versions later than that have issues, such as lack of Metal support, meaning you may not be able to use some softwares (Xcode, GarageBand, etc), or they will have some issues.
